---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: data-warehouse-dbt
  labels:
    app.kubernetes.io/name: data-warehouse-dbt
    app.kubernetes.io/part-of: data
    app.kubernetes.io/component: data
    app.kubernetes.io/version: 1.0.0
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dispatch
            image: 904333181156.dkr.ecr.sa-east-1.amazonaws.com/data-warehouse:$ECR_TAG
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
