version: 2

sources:
  - name: conformed
    database: dw001
    schema: conformed
    tables:
      - name: okr__user
      - name: okr__team
      - name: okr__team_users_user
      - name: okr__cycle
      - name: okr__objective
      - name: okr__key_result
      - name: okr__key_result_check_in
      - name: okr__key_result_comment
      - name: okr__key_result_check_mark
      - name: okr__key_result_support_team_members_user
      - name: okr__key_result_update
      - name: amplitude__events
      - name: analytics__company
      - name: analytics__key_result_progress_record
      - name: analytics__company_users_user
      - name: routines__answer
      - name: routines__answergroup
      - name: comm__comment
      - name: llm__llm_openaigeneration_subset_columns

models:
  - name: dim__user
    columns:
      - name: id
      - name: role
      - name: about
      - name: email
      - name: gender
      - name: picture
      - name: nickname
      - name: authz_sub
      - name: first_name
      - name: last_name
      - name: linked_in_profile_address
      - name: status
      - name: created_at
      - name: updated_at
      - name: type

  - name: dim__company
    columns:
      - name: id
      - name: team_id
      - name: name
      - name: type

  - name: dim__team
    columns:
      - name: id
      - name: name
      - name: gender
      - name: owner_id
      - name: parent_id
      - name: description
      - name: created_at
      - name: updated_at
      - name: company_id

  - name: dim__cycle
    columns:
      - name: id
      - name: active
      - name: period
      - name: cadence
      - name: team_id
      - name: date_start
      - name: date_end
      - name: parent_id
      - name: created_at
      - name: updated_at
      - name: company_id

  - name: dim__objective
    columns:
      - name: id
      - name: title
      - name: team_id
      - name: cycle_id
      - name: owner_id
      - name: created_at
      - name: updated_at
      - name: company_id

  - name: dim__key_result
    columns:
      - name: id
      - name: goal
      - name: type
      - name: title
      - name: format
      - name: team_id
      - name: owner_id
      - name: description
      - name: objective_id
      - name: cycle_id
      - name: initial_value
      - name: created_at
      - name: updated_at
      - name: company_id

  - name: dim__key_result_check_in
    columns:
      - name: id
      - name: value
      - name: comment
      - name: user_id
      - name: parent_id
      - name: confidence
      - name: key_result_id
      - name: created_at
      - name: objective_id
      - name: cycle_id
      - name: team_id
      - name: company_id

  - name: dim__key_result_comment
    columns:
      - name: id
      - name: text
      - name: user_id
      - name: key_result_id
      - name: created_at
      - name: updated_at
      - name: objective_id
      - name: cycle_id
      - name: team_id
      - name: company_id

  - name: dim__key_result_check_mark
    columns:
      - name: id
      - name: state
      - name: description
      - name: key_result_id
      - name: user_id
      - name: company_id
      - name: created_at
      - name: objective_id
      - name: cycle_id
      - name: team_id
      - name: updated_at

  - name: dim__amplitude_event
    columns:
      - name: id
      - name: user_id
      - name: event_time
      - name: event_type
      - name: event_properties

  - name: dim__answers
    columns:
      - name: id
      - name: value
      - name: question_id
      - name: answer_group_id

  - name: dim__answer_group
    columns:
      - name: id
      - name: user_id
      - name: company_id
      - name: timestamp

  - name: fct__user_accesses
    columns:
      - name: user_id
      - name: amplitude_event_id
      - name: access_time

  - name: fct__company_members
    columns:
      - name: company_id
      - name: user_id

  - name: fct__team_members
    columns:
      - name: team_id
      - name: user_id

  - name: fct__user_active_key_results
    columns:
      - name: user_id
      - name: key_result_id

  - name: fct__user_created_key_result_check_ins
    columns:
      - name: user_id
      - name: key_result_check_in_id
      - name: created_at

  - name: fct__user_created_key_result_comments
    columns:
      - name: user_id
      - name: key_result_comment_id
      - name: created_at

  - name: fct__user_received_key_result_comments
    columns:
      - name: user_id
      - name: author_id
      - name: key_result_comment_id
      - name: created_at

  - name: fct__key_result_latest_check_in
    columns:
      - name: key_result_id
      - name: key_result_check_in_id

  - name: fct__user_historic_progress
    columns:
      - name: user_id
      - name: progress
      - name: date

  - name: fct__user_active_progress
    columns:
      - name: user_id
      - name: progress
      - name: date

  - name: fct__user_cycle_progress
    columns:
      - name: user_id
      - name: cycle_id
      - name: progress
      - name: date

  - name: fct__user_cadence_progress
    columns:
      - name: user_id
      - name: cycle_id
      - name: cadence
      - name: progress
      - name: date

  - name: fct__team_historic_progress
    columns:
      - name: team_id
      - name: progress
      - name: date

  - name: fct__team_active_progress
    columns:
      - name: team_id
      - name: progress
      - name: date

  - name: fct__team_cycle_progress
    columns:
      - name: team_id
      - name: cycle_id
      - name: progress
      - name: date

  - name: fct__team_cadence_progress
    columns:
      - name: team_id
      - name: cycle_id
      - name: cadence
      - name: progress
      - name: date

  - name: fct__company_historic_progress
    columns:
      - name: company_id
      - name: progress
      - name: date

  - name: fct__company_active_progress
    columns:
      - name: company_id
      - name: progress
      - name: date

  - name: fct__company_cycle_progress
    columns:
      - name: company_id
      - name: cycle_id
      - name: progress
      - name: date

  - name: fct__company_cadence_progress
    columns:
      - name: company_id
      - name: cycle_id
      - name: cadence
      - name: progress
      - name: date

  - name: fct__cycle_progress
    columns:
      - name: cycle_id
      - name: progress
      - name: date

  - name: fct__key_result_progress
    columns:
      - name: key_result_id
      - name: progress
      - name: date

  - name: fct__key_result_progress_evolution
    columns:
      - name: key_result_id
      - name: key_result_check_in_id
      - name: progress
      - name: date

  - name: fct__user_activation
    columns:
      - name: user_id
      - name: first_access_amplitude_event_id
      - name: first_key_result_check_in_id
      - name: first_key_result_comment_id

  - name: fct__key_result_is_outdated
    columns:
      - name: key_result_id
      - name: latest_check_in_id
      - name: is_outdated
      - name: latest_check_in_date

  - name: fct__user_primary_team
    columns:
      - name: user_id
      - name: team_id

  - name: fct__user_primary_company
    columns:
      - name: user_id
      - name: company_id

  - name: fct__user_first_access
    columns:
      - name: user_id
      - name: amplitude_event_id

  - name: fct__user_last_access
    columns:
      - name: user_id
      - name: amplitude_event_id

  - name: fct__user_access_activation_delta
    columns:
      - name: user_id
      - name: delta

  - name: fct__user_first_key_result_check_in
    columns:
      - name: user_id
      - name: key_result_check_in_id

  - name: fct__user_checkin_activation_delta
    columns:
      - name: user_id
      - name: delta

  - name: fct__user_first_key_result_comment
    columns:
      - name: user_id
      - name: key_result_comment_id

  - name: fct__user_comment_activation_delta
    columns:
      - name: user_id
      - name: delta

  - name: fct__user_owned_key_results
    columns:
      - name: user_id
      - name: owned_key_results

  - name: fct__key_result_daily_average_progress
    columns:
      - name: key_result_id
      - name: key_result_check_in_id
      - name: day
      - name: progress

  - name: fct__key_result_amount_of_check_ins
    columns:
      - name: key_result_id
      - name: amount_of_check_ins

  - name: fct__user_first_access_per_week
    columns:
      - name: user_id
      - name: first_access_amplitude_event_id
      - name: week

  - name: fct__user_average_days_between_accesses
    columns:
      - name: user_id
      - name: average

  - name: fct__user_key_result_check_ins
    columns:
      - name: user_id
      - name: key_result_check_in_id
      - name: date

  - name: fct__user_first_key_result_check_in_per_week
    columns:
      - name: user_id
      - name: first_key_result_check_in_id
      - name: week

  - name: fct__user_average_days_between_key_result_check_ins
    columns:
      - name: user_id
      - name: average

  - name: fct__user_accesses_per_week
    columns:
      - name: user_id
      - name: week
      - name: accesses

  - name: fct__user_average_accesses_per_week
    columns:
      - name: user_id
      - name: average

  - name: fct__key_result_support_team
    columns:
      - name: key_result_id
      - name: user_id

  - name: fct__user_has_active_key_results
    columns:
      - name: user_id
      - name: owns_any
      - name: is_support_team_member_of_any

  - name: fct__key_result_amount_of_check_marks
    columns:
      - name: key_result_id
      - name: amount_of_check_marks

  - name: fct__user_amount_of_active_check_marks
    columns:
      - name: user_id
      - name: amount_of_active_check_marks

  - name: fct__daily_active_users
    columns:
      - name: day
      - name: amount_of_active_users

  - name: fct__weekly_active_users
    columns:
      - name: week
      - name: amount_of_active_users

  - name: fct__monthly_active_users
    columns:
      - name: month
      - name: amount_of_active_users

  - name: fct__user_is_active
    columns:
      - name: user_id
      - name: is_active

  - name: fct__users_per_month
    columns:
      - name: month
      - name: amount_of_users

  - name: fct__mau_routines_by_day
    columns:
      - name: day
      - name: user_type
      - name: flag_owns_team
      - name: company_id
      - name: unique_users
      - name: unique_active_users
      - name: mau

  - name: fct__wau_routines_by_day
    columns:
      - name: day
      - name: user_type
      - name: flag_owns_team
      - name: company_id
      - name: unique_users
      - name: unique_active_users
      - name: wau

  - name: fct__team_routines_above_half_fill
    columns:
      - name: week
      - name: teams_with_at_least_50_percent
      - name: total

  - name: fct__team_routines_stickness_by_day
    columns:
      - name: id
      - name: name
      - name: team_id
      - name: team_name
      - name: day
      - name: active
      - name: weekly_active
      - name: monthly_active
      - name: wau
      - name: mau
      - name: stickness

  - name: fct__team_routines_stickness_grouped_by_day
    columns:
      - name: day
      - name: teams_with_at_least_50_percent_wau
      - name: teams_with_at_least_50_percent_mau
      - name: wau
      - name: mau
      - name: stickness

  - name: fct__cohort_wau
    columns:
      - name: company_id
      - name: company_name
      - name: week0
      - name: week1
      - name: week2
      - name: week3
      - name: week4
      - name: week5
      - name: week6
      - name: week7
      - name: week8
      - name: week9
      - name: week10
      - name: week11
      - name: week12
      - name: week13
      - name: week14
      - name: week15
      - name: week16
      - name: week17
      - name: week18
      - name: week19
      - name: week20
      - name: week21
      - name: week22
      - name: week23
      - name: week24
      - name: week25
      - name: week26
      - name: week27
      - name: week28
      - name: week29
      - name: week30
      - name: week31
      - name: week32
      - name: week33
      - name: week34
      - name: week35
      - name: week36
      - name: week37
      - name: week38
      - name: week39
      - name: week40
      - name: week41
      - name: week42
      - name: week43
      - name: week44
      - name: week45
      - name: week46
      - name: week47
      - name: week48
      - name: week49
      - name: week50
      - name: week51
      - name: week52
      - name: week53
      - name: week54
      - name: week55
      - name: week56
      - name: week57
      - name: week58
      - name: week59
      - name: week60
      - name: week61
      - name: week62
      - name: week63
      - name: week64
      - name: week65
      - name: week66
      - name: week67
      - name: week68
      - name: week69
      - name: week70
      - name: week71
      - name: week72
      - name: week73
      - name: week74
      - name: week75
      - name: week76
      - name: week77
      - name: week78
      - name: week79
      - name: week80
      - name: week81
      - name: week82
      - name: week83
      - name: week84
      - name: week85
      - name: week86
      - name: week87
      - name: week88
      - name: week89
      - name: week90
      - name: week91
      - name: week92
      - name: week93
      - name: week94
      - name: week95
      - name: week96
      - name: week97
      - name: week98
      - name: week99
