version: 2
sources:
  - name: conformed
    tables: 
      - name: amplitude__events
        description: tbd
        meta:
          owner: igor.omote
      - name: analytics__company_users_user
        description: tbd 
        meta:
          owner: igor.omote
      - name: analytics__company
        description: tbd 
        meta:
          owner: igor.omote
      - name: analytics__key_result_progress_record
        description: tbd 
        meta:
          owner: igor.omote
      - name: okr__cycle
        description: tbd 
        meta:
          owner: igor.omote
      - name: okr__key_result_check_in
        description: tbd 
        meta:
          owner: igor.omote
      - name: okr__key_result_check_mark
        description: tbd 
        meta:
          owner: igor.omote
      - name: okr__key_result_comment
        description: tbd 
        meta:
          owner: igor.omote
      - name: okr__key_result_support_team_members_user
        description: tbd 
        meta:
          owner: igor.omote
      - name: okr__key_result
        description: tbd 
        meta:
          owner: igor.omote
      - name: okr__objective
        description: tbd 
        meta:
          owner: igor.omote
      - name: okr__team_users_user
        description: tbd 
        meta:
          owner: igor.omote
      - name: okr__team
        description: tbd 
        meta:
          owner: igor.omote
      - name: okr__user
        description: tbd 
        meta:
          owner: igor.omote